///////////////////////////////////////////////////////////
//  IMazeClient.cs
//  Implementation of the Interface IMazeClient
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////


using System;

namespace Mazegame.Boundary {
	public interface IMazeClient  {

		/// 
		/// <param name="question"></param>
		String GetReply(String question);

		/// 
		/// <param name="message"></param>
		void PlayerMessage(String message);
	}//end IMazeClient

}//end namespace Boundary