///////////////////////////////////////////////////////////
//  DungeonMaster.cs
//  Implementation of the Class DungeonMaster
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:36 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////


using System;
using Mazegame.Boundary;
using Mazegame.Entity;

namespace Mazegame.Control
{
    public class DungeonMaster
    {
        public IMazeClient gameClient;
        public IMazeData gameData;
        public Player thePlayer;

        public DungeonMaster(IMazeData gameData, IMazeClient gameClient)
        {
            this.gameData = gameData;
            this.gameClient = gameClient;
        }

        public void PrintWelcome()
        {
            gameClient.PlayerMessage(gameData.GetWelcomeMessage());
        }

        public void SetupPlayer()
        {
            String playerName = gameClient.GetReply("What name do you choose to be known by?");
            thePlayer = new Player(playerName);
            gameClient.PlayerMessage("Welcome " + playerName + "\n\n");
            gameClient.PlayerMessage("You find yourself looking at ");
            gameClient.PlayerMessage(gameData.GetStartingLocation().Description);

            gameClient.GetReply("<<Hit Enter to exit>>");
        }

        public void RunGame()
        {
            PrintWelcome();
            SetupPlayer();
        }
    } //end DungeonMaster
} //end namespace Control