///////////////////////////////////////////////////////////
//  Armor.cs
//  Implementation of the Class Armor
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:36 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

namespace Mazegame.Entity
{
    public class Armor : Item
    {
        public Armor()
        {
        }

        public int Bonus { get; set; }

        public override bool Equip(Player player)
        {
            player.Equip(this);
            return true;
        }
    } //end Armor
} //end namespace Entity