///////////////////////////////////////////////////////////
//  Blacksmith.cs
//  Implementation of the Class Blacksmith
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:36 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////


namespace Mazegame.Entity {
	public class Blacksmith : Shop {

		public Blacksmith(string description, string label) : base(description, label)
        {

		}


	}//end Blacksmith

}//end namespace Entity