///////////////////////////////////////////////////////////
//  Dice.cs
//  Implementation of the Class Dice
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:36 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////


namespace Mazegame.Entity
{
    public class Dice
    {
        private int rolls;
        private int sides;

        public Dice()
        {
        }

        public int Rolls
        {
            get { return rolls; }
            set { rolls = value; }
        }

        public int Sides
        {
            get { return sides; }
            set { sides = value; }
        }
    } //end Dice
} //end namespace Entity