///////////////////////////////////////////////////////////
//  Exit.cs
//  Implementation of the Class Exit
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity {
	public class Exit
	{
		public Exit(String description, Location destination)
		{
		    Description = description;
		    Destination = destination;
		}

	    public string Description { get; private set; }

	    public Location Destination { get; private set; }
    }//end Exit

}//end namespace Entity