///////////////////////////////////////////////////////////
//  Item.cs
//  Implementation of the Class Item
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

namespace Mazegame.Entity
{
    public class Item
    {
        public int Worth { get; set; }
        public int Weight { get; set; }
        public virtual string Description { get; set; }

        /// <summary>
        /// Equip player with item
        /// </summary>
        /// <param name="player"></param>
        /// <returns>Returns false if item can't be weared</returns>
        public virtual bool Equip(Player player)
        {
            return false;
        }
    } //end Item
} //end namespace Entity