///////////////////////////////////////////////////////////
//  Location.cs
//  Implementation of the Class Location
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace Mazegame.Entity {
	public class Location
	{
	    private Dictionary<string, Exit> exits = new Dictionary<string, Exit>();

	    public Location(string description,string label)
		{
		    Description = description;
		    Label = label;
		}

	    public void AddExit(string exitLabel, Exit theExit)
	    {
	        exits[exitLabel] = theExit;
	    }

		public string Description{ get; private set; }

	    public string Label { get; private set; }

        IReadOnlyDictionary<string, Exit> Exits { get { return exits; } }
    }//end Location

}//end namespace Entity