///////////////////////////////////////////////////////////
//  Maze.cs
//  Implementation of the Class Maze
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

namespace Mazegame.Entity {
	public class Maze {

		public Mazegame.Entity.Location m_Location;

		public Maze(){

		}

	}//end Maze

}//end namespace Entity