///////////////////////////////////////////////////////////
//  NonPlayerCharacter.cs
//  Implementation of the Class NonPlayerCharacter
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity
{
    public class NonPlayerCharacter : Character
    {
        public NonPlayerCharacter(string name, int agility, int lifePoints, int strength, bool hostile)
            : base(name, agility, lifePoints, strength)
        {
            Hostile = hostile;
        }

        public Boolean Hostile { get; private set; }
    }
}