///////////////////////////////////////////////////////////
//  Party.cs
//  Implementation of the Class Party
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System;

namespace Mazegame.Entity
{
    public class Party
    {
        public NonPlayerCharacter Character { get; set; }

        public Party()
        {
        }

        public Boolean Moveable { get; set; }
    } //end Party
} //end namespace Entity