///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace Mazegame.Entity {
	public class Player : Character {

		public Location Location { get; set; }
        public Location PreviousLocation { get; set; }

        public List<Item> Backpack { get; set; }
        public int MaxWeight => Strength * 2;

        public Player(string name, int agility, int lifePoints, int strength) 
            : base(name, agility, lifePoints, strength)
        {
            Backpack = new List<Item>();   
		}
	}
}