///////////////////////////////////////////////////////////
//  Shop.cs
//  Implementation of the Class Shop
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace Mazegame.Entity {
	public class Shop : Location {

		public Shop(string description, string label) : base(description, label)
        {
            Store = new List<Item>();
		}

        public List<Item> Store { get; set; }
	}
}