///////////////////////////////////////////////////////////
//  Shop.cs
//  Implementation of the Class Shop
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

namespace Mazegame.Entity {
	public class Shop : Location {

		public Shop(){

		}


	}//end Shop

}//end namespace Entity