///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Class Weapon
//  Generated by Enterprise Architect
//  Created on:      28-Apr-2014 10:13:37 PM
//  Original author: Gsimmons
///////////////////////////////////////////////////////////

namespace Mazegame.Entity {
	public class Weapon : Item {

		public Dice Dice { get; set; }

		public Weapon() {

		}

        public override string Description {
            get {
                return base.Description + $" (Dmg {Dice?.ToString()})";
            }
            set {
                base.Description = value;
            }
        }

        public override bool Equip(Player player)
        {
            player.Equip(this);
            return true;
        }
    }//end Weapon

}//end namespace Entity